restraunt/urls.py
from django.urls import path

from . import views

app_name = "restraunt"

urlpatterns = [
    # Create
    path("add/", views.Create.as_view(), name="add"),
    # Read
    path("", views.Index.as_view(), name="index"),
    path("<int:pk>/", views.Details.as_view(), name="details"),
    # Update
    path("<int:pk>/update/", views.Update.as_view(), name="update"),
    # Delete
    path("<int:pk>/delete/", views.Delete.as_view(), name="delete"),
]

restrauntManagementDjango/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("restraunt.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restraunt/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    food_name = models.CharField(max_length=200)
    food_price = models.IntegerField()
    food_discount = models.FloatField()
    food_image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.food_name

    def get_absolute_url(self):
        return reverse("restraunt:details", kwargs={"pk": self.pk})

restraunt/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item
from django.urls import reverse_lazy
# Create your views here.
class Index(generic.ListView):
    template_name="index.html"
    context_object_name="food_list"

    def get_queryset(self):
        return Item.objects.order_by("food_price")

class Details(generic.DetailView):
    model = Item
    template_name="detail.html"
    
class Create(generic.CreateView):
    model = Item
    template_name = "create.html"
    fields="__all__"

class Update(generic.UpdateView):
    model = Item
    template_name="create.html"
    fields="__all__"

class Delete(generic.DeleteView):
    model = Item
    template_name = "delete.html"
    success_url=reverse_lazy("restraunt:index")

restraunt/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Item</title>
</head>
<body>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="submit"/>
        <a href="{% url 'restraunt:index'%}">Back</a>
    </form>
</body>
</html>

restraunt/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <h2>Delete the food item "{{ object }}"?</h2>
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

restraunt/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item Details</title>
</head>
<body>
    <div style="padding: 2rem;">
        <a href="{% url 'restraunt:index'%}">Back</a>
        <a href="{% url 'restraunt:delete' item.id%}">Delete</a>
        <a href="{% url 'restraunt:update' item.id%}">Edit</a>
    </div>

    <img src="{{item.food_image.url}}" alt="" style="height: 500px ">
    <h3>{{item.food_name}}</h3>
    <h3>Rs. {{item.food_price}}</h3>
    <h3>{{item.food_discount}} %</h3>
    
</body>    

</html>

restraunt/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index View</title>
</head>
<body >
    {% if food_list %}
    <ul>
    {% for item in food_list %}
        <li>
            <a href="{% url 'restraunt:details' item.id %}">
                {{item.food_name}}
            </a>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <h1>Please add food items</h1>
    {% endif %}
    <a href="{% url 'restraunt:add'%}" >Add Item</a>
</body>
</html>